apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busysa
  name: busysa
spec:
  serviceAccountName:  testsalab
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: busysa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
