---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: secret
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-app
  name: secret-app
  namespace: secret
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "128Mi"
    name: secret-app
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
