apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: oldnginx
    type: canary
  name: oldnginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oldnginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oldnginx
        type: canary
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        resources: {}
        volumeMounts: 
            - name: indexfile
              mountPath: /usr/share/nginx/html/
      volumes: 
      - name: indexfile
        configMap:
          name: oldversion-cm
status: {}
